[project]
name = "aispikes"
version = "0.1.0"
description = "Various AI tests"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = ["spikes/thoughtful_ai"]
