[project]
name = "supervised-finetuning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.20.3",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.1",
    "trl>=0.15.2",
]
