[project]
name = "colpali-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colpali-engine>=0.3.8",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "pygments>=2.19.1",
]
